### ISSUE TITLE
Smalls symbol year not consistent with other futures

### ISSUE THREAD

**Issue by elescondite** [gotasty/tastypl#6]
smalls futures are live since June 1st but there is a problem with the symbol format... regular futures use a 1 digit year (0 = 2020, 1 = 2021), but smalls have a 2 digit year (20 = 2020). This causes the program to abort in futuresNotional():

```
Fri Jul 10 11:38:11 2020
F0710 11:38:26.411353   96364 tastypl.go:739] Don't know how much a point of /SFXN is worth in Bought 1 /SFXN20 @ 154.48
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc000071200, 0xc0001d4000, 0x79, 0xca)
	/Users/jrs/go/src/github.com/golang/glog/glog.go:769 +0xb8
github.com/golang/glog.(*loggingT).output(0x134f380, 0xc000000003, 0xc0001d2000, 0x12e52b7, 0xa, 0x2e3, 0x0)
	/Users/jrs/go/src/github.com/golang/glog/glog.go:720 +0x372
github.com/golang/glog.(*loggingT).printf(0x134f380, 0x3, 0x11b30d6, 0x30, 0xc000115c10, 0x2, 0x2)
	/Users/jrs/go/src/github.com/golang/glog/glog.go:655 +0x14b
github.com/golang/glog.Fatalf(...)
	/Users/jrs/go/src/github.com/golang/glog/glog.go:1148
main.futuresNotional(0xc00018f900, 0x10e784a, 0xc0001cdda0)
	/Users/jrs/src/tastypl/tastypl.go:739 +0x218
main.(*portfolio).handleTrade(0xc000154000, 0xc00018f900, 0xc000196101)
	/Users/jrs/src/tastypl/tastypl.go:766 +0x508
main.(*portfolio).handleTransaction(0xc000154000, 0xc00018f900)
	/Users/jrs/src/tastypl/tastypl.go:941 +0x4d0
main.NewPortfolio(0xc000148018, 0xb6, 0xff, 0x0, 0x100)
	/Users/jrs/src/tastypl/tastypl.go:451 +0x281
main.main()
	/Users/jrs/src/tastypl/tastypl.go:1578 +0x47d
exit status 255
```
CSV entry for smalls future /SFXN20

>2020-07-08T13:03:45-0400,Trade,BUY,/SFXN20,Future,Bought 1 /SFXN20 @ 154.48,0.00,1.0,0.00,-0.25,-0.20,,,,,

CSV entry for regular future /MESU0
>2020-06-26T10:45:42-0400,Trade,BUY,/MESU0,Future,Bought 1 /MESU0 @ 3019.25,0.00,1.0,0.00,-0.85,-0.52,,,,,

CSV entry for option on future /NGU0

> 2020-07-09T11:11:39-0400,Trade,BUY_TO_CLOSE,./NGU0 LNEU0 200826C2.3,Future Option,Bought 1 /NGU0 LNEU0 08/26/20 Call 2.300 @ 0.035,-350.00,1.0,-350.00,0.00,-1.82,1,/NGU0,8/26/20,2.3,CALL

I just started looking at this program today so I haven't got my head around the internals yet to find the best place to fix it. The offending lines in futuresNotional() and ParsePrice() are:

```
	contract := tx.underlying[:len(tx.underlying)-2]
	pointValue, ok := futuresPoints[contract]
```
Which sets contract to /SFXN, not /SFX. 

It seems to me we need an isSmalls flag/function and a generalized getContract() function for futures rather than hard coding. Storing the flag and contract string in the transaction struct seems appropriate after studying the code for 5 minutes ;-)

Thoughts?

**Comment by elescondite** [comment]
Made a quick hack until a real go programmer comes along ;-)

https://github.com/elescondite/tastypl/commit/88aa27e876f25a90c6fcfb8bf895095a3fe26785
